# Numpy

In [54]:
import numpy as np

In [55]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
b = np.random.random((3, 4)) * 5

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
b

array([[3.9005333 , 3.29911092, 4.30970131, 3.70992968],
       [3.8751981 , 2.11981405, 0.21914528, 0.68446153],
       [0.04381039, 3.68567579, 4.66463887, 0.85071152]])

In [57]:
a * b

array([[ 3.9005333 ,  6.59822184, 12.92910393, 14.83971871],
       [19.37599049, 12.71888428,  1.53401694,  5.4756922 ],
       [ 0.39429354, 36.85675794, 51.31102753, 10.20853825]])

In [58]:
a > b

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
a[a > b]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
a.mean()

np.float64(6.5)

In [61]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Linear Algebra Refresher

## Vector Multiplication (dot product)

In [62]:
u = np.array([3,6,8,1])
u

array([3, 6, 8, 1])

In [63]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [64]:
print(u.shape, v.shape)

(4,) (4,)


In [65]:
# Dot product
def dot_product(u,v):
    assert u.shape[0] == v.shape[0] # same row count

    result = 0
    for i,j in zip(u,v):
        r = i * j
        result += r
    return result

dot_product(u,v)


np.int64(43)

In [66]:
u.dot(v)

np.int64(43)

## Matrix-Vector Multiplication

In [67]:
u = np.array([
    [3,6,8,1],
    [4,5,6,7],
    [1,2,3,4]
])

v = np.array(
    [
        4,
        2,
        3,
        6
    ]
)

print(u.shape, v.shape)

(3, 4) (4,)


In [68]:
v

array([4, 2, 3, 6])

In [ ]:
def matrix_vector_prod(m, v):
    # The # of cols from the matrix should 
    # be the same # of row from the vector
    # for example: (3,4) x (4,) -> (3,) {rows, cols}
    
    assert m.shape[1] == v.shape[0] 

    rows = m.shape[0]

    result = np.zeros(rows)
    for i in range(rows):

        suma = (m[i] * v).sum()
        result[i] = suma

    return result

matrix_vector_prod(u,v)

array([54., 86., 41.])

## Matrix-Matrix Multiplication

In [69]:
def matrix_matrix_product(a, b):

    # Matrix a shape
    cols_matrix_a = a.shape[1]
    rows_matrix_a = a.shape[0]
    # Matrix b shape
    cols_matrix_b = b.shape[1]
    rows_matrix_b = b.shape[0]

    assert cols_matrix_a == rows_matrix_b # cols of a == rows of b
    # For example (6,7) x (7,3) -> (6,3)

    # Now we need to get the first row from matrix a (the matrix on the left)
    # and multiuply each element by the matching vector from matrix b columns
    # and finally sum all the multiplications of the elements
    
    result_matrix_zeros = np.zeros((rows_matrix_a, cols_matrix_b))

    for row in range(rows_matrix_a):
        # for example row 0
        row_vector = a[row,:]
        for col in range(cols_matrix_b):
            col_vector = b[:,col]

            result_vector = row_vector*col_vector
            result_cell_element = result_vector.sum()

            result_matrix_zeros[row, col] = result_cell_element

    return result_matrix_zeros



In [70]:
matrix_matrix_product(
    np.array([[2,1,3],[3,2,4]]), 
    np.array([[2,0,3,4], [3,1,2,9], [1,2,1,2]])
)

array([[10.,  7., 11., 23.],
       [16., 10., 17., 38.]])

# Pandas

is not necessary to learn pandas because I know it very well